on:  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/k8s-set-context@v1
      with:
       method: kubeconfig
       kubeconfig: ${{ secrets.KUBECONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)

    - uses: Azure/k8s-deploy@v1
      with:
        namespace: oakyak
        manifests: deployment.yaml
